version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - docker_state_exporter
    - cadvisor
  docker_state_exporter:
    image: karugaru/docker_state_exporter
    container_name: dockerstateexporter
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target:  /var/run/docker.sock
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    privileged: true 
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro 
    - /var/run:/var/run:ro 
    - /sys:/sys:ro 
    - /var/lib/docker/:/var/lib/docker:ro 
    - /dev/disk/:/dev/disk:ro 
    devices:
    - /dev/kmsg 
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'