{
 "title": "Mutsar Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Mutsar Running Container",
   "type": "gauge",
   "description": "This Will Show the number of container running under Mutsar application",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_state_status{status=\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mustsar Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mutsar Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=~\"/docker/f764a908f6735ef619a59f22b5bc4f218e47f4cf6c5ad84272e1464b68c73601|/docker/455d6bc7137e3cea00e12d905a97ee900f96cd58755047ad5555d077cc2985c6|/docker/a0b2454c7036a75ab5c3d828261ae849096aad752361c7e105be5e2678e43dfe|/docker/b707e512fb8df0b21be9ef05c6f81fe0cb097a80840e448319d6d4506a31b252|/docker/807f77fad0e150f75d871a843b668e541b44d8010d471f080e30d46f05edc49a|/docker/be21de4717769184f9e81cfbabc13cb2a0d23ca9d8c479734e6ae62c992e399f|/docker/5e0237cdff75c6423640c781ab9c05d38b06e23f83e1d537413614abb036e9d4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(id) (rate(container_network_receive_bytes_total{id=~\"/\"}[5s]))",
     "legendFormat": "{{RECEIVED}}"
    },
    {
     "expr": "- sum by(id)  (rate(container_network_transmit_bytes_total{id=~\"/\"}[5s]))",
     "legendFormat": "{{SENT}}"
    }
   ]
  },
  {
   "title": "Mutsar Running Container",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "container_tasks_state{id=~\"/docker/455d6bc7137e3cea00e12d905a97ee900f96cd58755047ad5555d077cc2985c6|/docker/5e0237cdff75c6423640c781ab9c05d38b06e23f83e1d537413614abb036e9d4|/docker/807f77fad0e150f75d871a843b668e541b44d8010d471f080e30d46f05edc49a|/docker/a0b2454c7036a75ab5c3d828261ae849096aad752361c7e105be5e2678e43dfe|/docker/b707e512fb8df0b21be9ef05c6f81fe0cb097a80840e448319d6d4506a31b252|/docker/be21de4717769184f9e81cfbabc13cb2a0d23ca9d8c479734e6ae62c992e399f|/docker/f764a908f6735ef619a59f22b5bc4f218e47f4cf6c5ad84272e1464b68c73601\"} and container_tasks_state{state=\"running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mutsar Unhealthy Container (Ref. Value In Red)",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 17 },
   "targets": [
    {
     "expr": "container_state_status{id=~\"/docker/a0b2454c7036a75ab5c3d828261ae849096aad752361c7e105be5e2678e43dfe|/docker/455d6bc7137e3cea00e12d905a97ee900f96cd58755047ad5555d077cc2985c6|/docker/f764a908f6735ef619a59f22b5bc4f218e47f4cf6c5ad84272e1464b68c73601|/docker/807f77fad0e150f75d871a843b668e541b44d8010d471f080e30d46f05edc49a|/docker/b707e512fb8df0b21be9ef05c6f81fe0cb097a80840e448319d6d4506a31b252|/docker/5e0237cdff75c6423640c781ab9c05d38b06e23f83e1d537413614abb036e9d4|/docker/be21de4717769184f9e81cfbabc13cb2a0d23ca9d8c479734e6ae62c992e399f\"} and container_state_status{status=\"exited\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mutsar Container Name & ID",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "container_state_health_status{id=~\"/docker/a0b2454c7036a75ab5c3d828261ae849096aad752361c7e105be5e2678e43dfe|/docker/455d6bc7137e3cea00e12d905a97ee900f96cd58755047ad5555d077cc2985c6|/docker/f764a908f6735ef619a59f22b5bc4f218e47f4cf6c5ad84272e1464b68c73601|/docker/807f77fad0e150f75d871a843b668e541b44d8010d471f080e30d46f05edc49a|/docker/b707e512fb8df0b21be9ef05c6f81fe0cb097a80840e448319d6d4506a31b252|/docker/5e0237cdff75c6423640c781ab9c05d38b06e23f83e1d537413614abb036e9d4|/docker/be21de4717769184f9e81cfbabc13cb2a0d23ca9d8c479734e6ae62c992e399f\"} and container_state_health_status{status=\"healthy\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}